dwijnand/sbt-extras

sbt, test/download.bats, test/test_helper.bash
@paulp this is a proposition to resolve #93 and restore a behaviour that was previously introduced by #44. 
Note that this "feature" is now covered by two unit tests for Windows format (CRLF) and Unix format (LF), but not for Mac-OS9 (CR).
//cc @MikeHoffert @szeiger
=> Trim "\r" in sbt.version line of build.properties

sbt
OpenJDK 8 identifies itself as "openjdk" rather than "java" in the
output of `java -version`. the regular expression by grep used for java
version detection has been modified to handle both forms. the modified
form only uses grep arguments defined within the POSIX specification.
this modified version has been tested against the following operating
systems: Debian 8, Fedora 21, CentOS 7, Ubuntu 14.04, Ubuntu 14.10 and
Mac OS X 10.10 with a variety of JVMs. For completeness the
`java -version` output from a number of these operating systems has been
provided below:
Debian 8:
$ /usr/lib/jvm/java-1.6.0-openjdk-amd64/bin/java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
$ …
=> add openjdk 8 version detection

README.md, sbt, test/download.bats, test/test_helper.bash
Looking in https://repo.typesafe.com/typesafe/ivy-releases it seems the current
version-matching rules in mark_url would continue to work with this new
repository, and it includes 0.13.9-M1, which is missing in artifactoryonline.
=> Update to v0.13.9 & update to new ivy repo URL

sbt
Currently, if `~/.sbtignore` exists, sbt-extras would return 0 even if the `sbt` command failed
e.g.,
```
$ rm ~/.sbtignore
$ ./sbt -sbt-create asdfg; echo "exit status was $?"
[info] Set current project to sbt-extras (in build file:/private/tmp/sbt-extras/)
[error] Not a valid command: asdfg (similar: last)
[error] Not a valid project ID: asdfg
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: asdfg (similar: tags)
[error] asdfg
[error]      ^
exit status was 1
$ touch ~/.sbtignore
$ ./sbt -sbt-create asdfg; echo "exit status was $?"
Starting sbt with output filtering enabled.
[info] Set current project to sbt-extras (in build file:/private/tmp/sbt-extras/)
[error] Not a valid command: asdfg (similar: last)
[error] Not a valid project ID: asdfg
[error] Expected …
```
=> Correct exit status when output filtering enabled

.travis.yml, bin/run-tests
Add OS X as a target OS, giving us better coverage of BSD-variants of the
userland tools (grep, sed, etc). Note that this increases the build from ~40s to
~1m30.
Kill JDKs as they weren't needed and were misleading. Note that both Linux and
OS X docker containers have Java 7 installed, but the tests never use Java.
Configure Gitter webhook for Travis
Also attempt to speed up the build by using git depth. Doesn't seem to have much
of an effect, but it can't hurt.
Closes #126
Superseeds #127
=> Setup Travis for OS X, Gitter & speed

sbt, test/scala.bats
Allows the sbt launcher to work on projects that are crazy enough to
compile their meta-projects with `-Yno-imports`.
=> Fully-qualify names in generated .scala file.

.travis.yml
This reverts the principle change in #129.
Continuing from where that commit message left off, the reason that the tests
never use Java is that's how bats works: nothing on the PATH is used.
Therefore there's no strong reason to test on both Linux and OS X as it's only
testing potential variations of whatever version of bash is running.
So dropping OS X support reduces the travis setup and recovers some speed in the
builds (hopefully back to ~40s from ~1m30).
Note OS X support might come back with #132.
=> Drop OS X support for Travis..

sbt
Works with gnu sed but not the sed which ships with OSX.
Isn't necessary for our regex anyway, it seems.
=> Remove -r option to sed.

sbt
Use the sbt snapshots repo for timestamped versions, ie. of shape `*-yyyymmdd-hhMMss`, such as https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.10-20151229-205306/.
=> Use sbt ivy-snapshots repo for timestamped sbt versions

README.md, sbt, test/options.bats
This is a very naive implementation in order to support running scala scripts, even in folders that do not contain sbt projects. Saving the following snippet 
```scala
/***
libraryDependencies += "com.github.lalyos" % "jfiglet" % "0.0.7"
*/
import com.github.lalyos.jfiglet.FigletFont;
val msg = if (args.size > 0) args.mkString(" ") else ""
val asciiArt = FigletFont.convertOneLine(s"hello $msg!");
System.out.println(asciiArt);
```
and running `sbt -script snippet.scala sbt extra` yields
```
[info] Loading global plugins from /home/user/.sbt/0.13/plugins
[info] Set current project to cc88a3ff57276e4d8968 (in build file:/home/user/.sbt/boot/cc88a3ff57276e4d8968/)
_            _  _               _      _                 _                 _ 
| |__    ___ | || |  ___    ___ | |__  | |_    ___ …
```
=> Add the possibility to run scala scripts

sbt, test/scala.bats
Addresses a problem introduced by 1e6c083 when overriding `scalaHome` or `javaHome` in conjunction with using a plugin that contains a member named `scala`.
=> Use absolute package for fully qualified names

sbt
It's an upstream bug that has been fixed already, but hasn't been
released yet, tracked under Azul report 7781 (I can't find an online
ticket for it and probably finding the fixed commit means investigating
mercurial)
=> tiered compilation core dumps recent OpenJDK

sbt
Before this commit, an empty $JAVA_HOME will cause sbt to check existence
of the path "/bin/java".
While this path does exist, it's obvious that $JAVA_HOME is broken.
This commit makes sbt avoid unbound variables.
=> disallow unbound environment variables

sbt
Fix for alpine linux with BusyBox v1.24.2:
`wget: unrecognized option: quiet`
=> Fix `wget: unrecognized option: quiet`

sbt
Based in part on
http://xmlandmore.blogspot.com/2014/08/jdk-8-revisiting-reservedcodecachesize.html
I think these options are doing more harm than good and need to be
remotivated or removed.
=> Remove some default jvm options.

sbt
Instead warn if there is a Java version mismatch between PATH and JAVA_HOME/JDK_HOME.
In more detail this:
* reverts most of #95: setting javaHome via JAVA_HOME
* reverts most of #96: setting javaHome via JDK_HOME
* fixes #99: unbreaking sbt-extras possibly up to sbt version 0.11.2
* fixes #122: unbreaks sbt.ScriptMain, see #122 for an example scrit that now works
---
Superseeds #154.
=> Drop setJavaHomeQuietly via JAVA_HOME/JDK_HOME

sbt
=> Use ~/.ivy2/local before downloading sbt-launch.jar

.appveyor.yml, .gitattributes, .gitignore, bin/relinkSymlinks.sh, bin/run-tests, sbt, test/test_helper.bash
Anything against this? Now I can run it as well from windows.
=> cygwin support

README.md
I'm not sure if this was always wrong or if something changed.  AppVeyor
isn't helping by having 2 diverse ways of identifying the same project..
Either way this makes the badge (currently green) match the build (also
currently green).
Fixes #190
=> Fix the AppVeyor badge URL

sbt
Discovered when executing
sbt -sbt-version 0.13.16-SNAPSHOT new scala/scala-seed.g8
It would use sbt 0.13.15, because that's the current
sbt_release_version.
=> Don't overwrite sbt_explicit_version

README.md
This is a lot shorter and more memorable than the original
raw.githubusercontent.com version.
This is a retake on my attempt in #78 (in 2014!), with the following
benefits:
* Uses GitHub-owned git.io URL shortener rather than the third-party
tinyurl.com
* It's shortened with "sbt" rather than "paulp-sbt" this time round
Unfortunately I couldn't shorten
https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt or
http://github.com/paulp/sbt-extras/raw/master/sbt directly because they
already had associated generated codes, so couldn't be associated to the
"sbt" code. So I'm using
https://raw.github.com/paulp/sbt-extras/master/sbt.
Are you on a machine and want sbt? You just have to curl git.io/sbt.
Both https and http work.
Reference:
$ curl -IL https://git.io/sbt
HTTP/1.1 302 Found …
=> Switch to https://git.io/sbt in the README

sbt
The link added to the original repository helps users update the script and helps developers find the community.
=> Add link to the original repository

sbt
The use of `command` in place of `which` is more portable. In our case, we run our builds in Docker containers and the centos7 image no longer ships with `which`.  There's a very detailed analysis of `which` and its alternatives here:
https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
tl/dr; To find out if a given command exists:
```
if command -v given-command > /dev/null 2>&1; then
echo given-command is available
else
echo given-command is not available
fi
```
=> Switch from which to command to determine whether curl or wget is installed.

README.md, sbt, test/scala.bats
Apr 27
https://github.com/scala/scala/releases/tag/v2.12.6
Jan 31
https://github.com/scala/scala/releases/tag/v2.13.0-M3
=> Scala 2.12.6, 2.13.0-M3

sbt
.. rather than modifying build.properties.
From archeology it looks like back in Feb 2012, when sbt 0.11.2 [1] was
the latest and greatest and 0.12.0-M1 [2] was out, the sbt.version in
build.properties was the only way to specify to sbt's launcher the
version of sbt to launch [3].
[1]: https://github.com/sbt/sbt/releases/tag/v0.11.2
[2]: https://github.com/sbt/sbt/releases/tag/v0.12.0-M1
[3]: https://github.com/paulp/sbt-extras/commit/7bfd06dc51b815087267f8ee3a9a35b94c1b0cf8
However a few months later, in May 2012, Mark added support [4] for the
sbt.version system property, support which shipped in the following sbt
0.11.x releases and 0.12.x pre-releases.
[4]: https://github.com/sbt/sbt/commit/f39af0bab3e3d4ab3e756864c6adecfd21a5f9c9
Therefore, this patch makes sbt_explicit_version not …
=> Switch sbt_explicit_version to use -Dsbt.version

sbt, test/basic.bats
I suggest removing this configuration in order to give sbt more memory.
The JVM should give 1/4th of the physical memory. This can be verified by running:
java -XX:+PrintFlagsFinal -version | grep MaxHeapSize
Since computers of at least 6 GB of physical memory became more common, I suggest removing this constraint.
=> Remove maximum Java heap size (MaxHeapSize)

README.md, sbt, test/scala.bats
Per https://github.com/scala/scala/releases/tag/v2.13.0-M5
~~This would be the change but I haven't had success pulling from Maven yet.~~
Edit: Seems okay now.
=> scala 2.13.0-M5

README.md, sbt, test/test_helper.bash
No rush on merging. Not even sure what's in `0.13.18`! But this is what the change would be.
https://github.com/sbt/sbt/releases/tag/v0.13.18
Edit: Release notes were blank at the time but they have since been updated.
=> update sbt to 0.13.18

sbt, test/download.bats
It's displayed for the launcher jar so perhaps show it for the md5 file, too.
I encountered a problem today wherein I suspected that the MD5 file URL was getting munged by a corporate firewall, so I exposed the URL in this manner. It seems worthwhile to notify the user that a file is being downloaded and the URL from while it is being retrieved.
=> Displays log output when retrieving md5 files

sbt
- This program is distributed under the `LICENSE.txt` and it requires: 
> - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution
- But some libraries (for exapmle, [Scalaz](https://github.com/scalaz/scalaz/blob/master/sbt)) may not follow these sentences.... 😇 
- As I'm not an expert of lows nor licenses, I think these libraries which are using `sbt` don't want to violate the license
- They are just using `sbt` because it's very useful
- In my opinion, if the license would be also written into `sbt` file, then …
=> Add license to `sbt` for the redistributions

sbt
along with `-sbt-extras-opts` and `$SBT_EXTRAS_OPTS`.
This will be useful for settings like `-sbt-launch-repo`.
fixes https://github.com/paulp/sbt-extras/issues/272
---
Note: I would find it preferable, if vanilla sbt ignored unrecognized parameters (as suggested in https://github.com/sbt/sbt/issues/5486 ), but it that won't happen we can merge this. Or we can merge this to have a workaround in the meantime.
=> Introduce .sbtextrasopts

sbt
This PR will enable running sbt-extra script under Apple Silicon (M1).
Currently, JVMCI interface is not supported in JVMs built for Apple Silicon (M1, Darwin arm64). This fix is a workaround for the error reported in #297. 
A downside of this fix is that this will disable using JVMCI compiler option if the user is using a JVM built for x64, but running with Rosetta2, which is a x64 - arm64 compatibility layer of M1. But, it was a bit difficult to check whether the jvm supports JVMCI or not without running any Java program. If we can run some Java code, we can check the availability of JVMCI compiler by looking at `java.vm.version` system property, but this would be overkill for a light-weight script like sbt-extras.
=> Fixes #297: Support Apple Silicon (M1)

sbt, test/download.bats
The un-version-tagged jar is the exception: version tagging is the norm
for maven publishing.  I think the unversioned jar was a historical
(mild) accident.  Changing back to it seems to me as an unintentional
part of the switch to Maven Central.
Fixes #309
=> Restore fetching the version-tagged launch jar

.github/workflows/test.yml
Fix to run ci whenever an outside collaborator tries to open a PR.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
=> Add pull_request trigger

README.md
This is needed to install using `brew`.
```zsh
% brew install --HEAD paulp/extras/sbtx   
Warning: No available formula or cask with the name "paulp/extras/sbtx". Did you mean paulp/extras/z3 or paulp/extras/wbrew?
```
=> doc: correct Homebrew installation command

README.md, sbt, test/scala.bats
https://github.com/scala/scala/releases/tag/v2.12.20
=> scala 2.12.20
