sbt
test/test_helper.bash

Support $JDK_HOME.

---

sbt
test/config-file.bats

Taken from http://stackoverflow.com/q/4165135/463761
Fixes #97

Read last lines which end with EOF

---

README.md
sbt
test/config-file.bats
test/download.bats
test/test_helper.bash

> sbt 0.13.10 did not happen due a bug that was found after the artifact was published.
http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt+0.13.10

Upgrade to sbt 0.13.11

---

sbt

From:
* https://github.com/sbt/sbt-launcher-package/commit/289acc3b82b415f670594065024d2e819197d522#diff-fdc3abdfd754eeb24090dbd90aeec2ceR129
* https://github.com/sbt/sbt/commit/fd7c162ea802008cf3586943c0ba9d862a677502#diff-fdc3abdfd754eeb24090dbd90aeec2ceR15

Add support for maven repos under 1.x

---

README.md
sbt
test/test_helper.bash

Updated dev version to RC2, added appveyor badge, dropped
section on .sbtignore since I'm not actually using it.

README and related updates.

---

sbt
test/help.bats

Exit code 0 on a call to -help.

---

README.md
sbt
test/scala.bats

Revert "scala 2.11.9"

---

README.md
sbt
test/scala.bats

TUESDAY 17 OCTOBER 2017
https://www.scala-lang.org/news/2.12.4

scala 2.12.4

---

README.md
sbt
test/scala.bats

Nov 9
https://github.com/scala/scala/releases

scala 2.10.7, scala 2.11.12

---

README.md
sbt
test/test_helper.bash

An SBT upgrade with the `0.13` series.
Jan 31 - https://github.com/sbt/sbt/releases/tag/v0.13.17

sbt 0.13.17

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.7

scala 2.12.7

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.8

scala 2.12.8

---

.travis.yml

switch travis base image to minimal

---

README.md
sbt
test/download.bats
test/sbt-1.1.bats
test/sbt-1.bats
test/test_helper.bash

Update fallback sbt version to 1.2.8

---

.travis.yml
sbt

Resolve shellcheck warnings & run shellcheck on Travis CI

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.0-RC1

scala 2.13.0-RC1

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.0-RC2

scala 2.13.0-RC2

---

README.md
sbt
test/test_helper.bash

https://www.lightbend.com/blog/sbt-1.3.0-release

sbt 1.3.0-RC1

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.0-RC3

scala 2.13.0-RC3

---

README.md
sbt
test/scala.bats
test/test_helper.bash

- https://github.com/scala/scala/releases
- https://github.com/sbt/sbt/releases

scala 2.13.1 + sbt 1.3.1

---

.travis.yml
README.md
sbt

Enforce formatting

---

README.md
sbt

Drop .sbtignore support

---

sbt
test/basic.bats

Add -XX:MaxInlineLevel=18 to default_jvm_opts_common

---

README.md
sbt
test/test_helper.bash

Used `fastmod 1.3.6 1.3.7`. Diff looks like #265

Bumps sbt to 1.3.7

---

sbt
test/options.bats

Set coursier home under -no-share

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.11
```bash
cd bin
/run-tests
```

scala 2.12.11

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.3.10

sbt 1.3.10

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.2

scala 2.13.2

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.3.12

sbt 1.3.12

---

sbt
test/test_helper.bash

http://eed3si9n.com/sbt-1.4.0-beta

sbt 1.4.0-M1

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.3

scala 2.13.3

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.3.13

sbt 1.3.13

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.12

scala 2.12.12

---

README.md

repo.scala-sbt.org shut off http access today, is why this came up :-)

correct small mistake in readme

---

sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.4.0-RC1

sbt 1.4.0-RC1

---

sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.4.0-RC2

sbt 1.4.0-RC2

---

sbt
test/download.bats

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ 😢

use maven central for download sbt-launcher

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.5

scala 2.13.5

---

sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.5.0-M2

sbt 1.5.0-M2

---

.github/workflows/test.yml
.travis.yml

Use GitHub Actions instead of Travis CI

---

README.md
sbt
test/scala.bats
test/test_helper.bash

https://github.com/scala/scala/releases/tag/v2.12.13
https://github.com/sbt/sbt/releases/tag/v1.5.0-RC2

scala 2.12.13 + sbt 1.5.0 RC1

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.15

scala 2.12.15

---

sbt

Parse java versions with `-ea` suffix

---

sbt

fix https://github.com/dwijnand/sbt-extras/issues/331

remove `-XX:+UseJVMCICompiler` if JDK 17

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.8

scala 2.13.8

---

sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.7.0-M2

sbt 1.7.0-M2

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.16

scala 2.12.16

---

sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.7.0-RC1

sbt 1.7.0-RC1

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.9

scala 2.13.9

---

README.md
sbt
test/scala.bats

https://github.com/scalacenter/scalafix/issues/1684

scala 2.13.10

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.12.17

scala 2.12.17

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.9.0-RC3

sbt 1.9.0-RC3

---

README.md
sbt
test/scala.bats

- https://github.com/scala/scala/releases/tag/v2.12.18
- https://github.com/scala/scala/releases/tag/v2.13.11

scala 2.12.18 and scala 2.13.11

---

README.md
sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.12

scala 2.13.12

---

README.md
sbt
test/scala.bats

- https://github.com/scala/scala/releases/tag/v2.12.19
- https://github.com/scala/scala/releases/tag/v2.13.13

scala 2.12.19; scala 2.13.13

---

sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.14

scala 2.13.14

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.0

sbt 1.10.0

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.1

sbt 1.10.1

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.2

sbt 1.10.2

---

sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.15

scala 2.13.15

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.3

sbt 1.10.3

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.4

sbt 1.10.4

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.5

sbt 1.10.5

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.10

sbt 1.10.10

---

sbt
test/scala.bats

https://github.com/scala/scala/releases/tag/v2.13.16

scala 2.13.16

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.10.11

sbt 1.10.11

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.11.0

sbt 1.11.0

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.11.2

sbt 1.11.2

---

README.md
sbt
test/test_helper.bash

https://github.com/sbt/sbt/releases/tag/v1.11.5

sbt 1.11.5
